### ISSUE TITLE
add GIF of live website to readme file

### ISSUE THREAD

**Issue by gulshanjakhon** [gulshanjakhon/ShopKaro#2]
website live at https://gulshanjakhon.github.io/ShopKaro/

**Comment by YuriCodes** [comment]
Hello, i'd like to work on this!

**Comment by gulshanjakhon** [comment]
you can go head @YuriCodes 
Best Of luck !🙌

**Comment by YuriCodes** [comment]
Thank you! I already did it, it's on PR#3. : )
